### ISSUE TITLE
Page transition does not scroll up on Firefox

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster.github.io#11]
Clicking on the news at the bottom does not scroll up to the top when using firefox

**Comment by vin-ni** [comment]
@capital-G Is your firefox up to date? Works fine on mine

v 111

**Comment by p6gb** [comment]
For me it also doesn't scroll up for the news that are linked from `index.html`.

**Comment by vin-ni** [comment]
Or maybe we just turn it off
https://github.com/nuxt/nuxt/discussions/18757

**Comment by vin-ni** [comment]
@capital-G could you check this again?
I think it has been resolved with my recent css updates

**Comment by capital-G** [comment]
Works perfectly now! Thanks for the fix!
